name       : python-sphinxcontrib-jquery
version    : '4.1'
release    : 1
source     :
    - https://github.com/sphinx-contrib/jquery/archive/refs/tags/v4.1.tar.gz : f6a7578b00a8458e5edd38431d3ea4037b928a21ba1f82469ec2015127955c34
homepage   : https://github.com/sphinx-contrib/jquery
license    : 0BSD
component  : programming.python
summary    : Extension to include jQuery on newer Sphinx releases
description: |
    sphinxcontrib-jquery ensures that jQuery is always installed for use in Sphinx themes or extensions.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-pytest    # check
    - python-sphinx    # check
rundeps    :
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
